title: NLP Professors in Indian Universities
description: To update the list please add details [here](https://docs.google.com/forms/d/e/1FAIpQLSfFxwkHgBnjzppLYAZy3HgJy21yu20Fx95q52b7CpzjMOxL-g/viewform) or send a [pull](https://github.com/nlpbharat/nlpbharat.github.io) request. 
 
google_analytics: UA-179831510-1

theme: jekyll-theme-cayman
